services:
  app:
    container_name: feed_app
    build:
      context: ../
      dockerfile: ./Dockerfile
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - db

  db:
    container_name: feed_db
    image: postgres:17.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always